apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
  namespace: static
  labels:
    app: nginx-static
spec:
  containers:
    - name: nginx-static
      image: nginx:alpine
      ports:
        - containerPort: 80
