apiVersion: v1
kind: Pod
metadata:
  name: redis-db
  namespace: trouble
  labels:
    name: redis-db
spec:
  containers:
    - name: redis-db
      image: busybox
      command: ["sh", "-c"]
      args: ["sleep infinity"]
  restartPolicy: Always
